++Readme. Update hspm and recipes

diff --git a/bin/hspm/recipes/Darwin/recipe-brew b/bin/hspm/recipes/Darwin/recipe-brew
--- a/bin/hspm/recipes/Darwin/recipe-brew
+++ b/bin/hspm/recipes/Darwin/recipe-brew
@@ -1,18 +1,22 @@
 function about() {
     echo "The missing package manager for macOS"
-    return 0
 }
 
 function depends() {
+    if [ command -v ruby >/dev/null ]; then
+        echo "${RED}Ruby is required to install HomeBrew${NC}"
+        return 1
+    fi
+
     return 0
 }
 
 function install() {
-    echo 'Installing HomeBrew ...'
-    return 0
+    command ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+    return $?
 }
 
 function uninstall() {
-    echo 'Uninstalling HomeBrew ...'
-    return 0
+    command ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
+    return $?
 }
diff --git a/bin/hspm/recipes/Darwin/recipe-htop b/bin/hspm/recipes/Darwin/recipe-htop
--- a/bin/hspm/recipes/Darwin/recipe-htop
+++ b/bin/hspm/recipes/Darwin/recipe-htop
@@ -1,18 +1,22 @@
 function about() {
-    echo "A better TOP"
-    return 0
+    echo "An interactive process viewer for Unix"
 }
 
 function depends() {
+    if [ command -v brew >/dev/null ]; then
+        echo "${RED}HomeBrew is required to install HomeBrew${NC}"
+        return 1
+    fi
+
     return 0
 }
 
 function install() {
-    echo 'Installing Htop...'
-    return 0
+    command brew instal htop
+    return $?
 }
 
 function uninstall() {
-    echo 'Uninstalling Htop ...'
-    return 0
+    command brew uninstal htop
+    return $?
 }
