Improve GitHub actions

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -16,12 +16,12 @@ on:
         type: boolean
   push:
     branches:
-      - '**'
+      - 'master'
     paths:
       - 'bin/**'
       - 'dotfiles/**'
       - 'tests/**'
-      - '*.bash'
+      - '**/*.bash'
   fork:
     branches:
       - '**'
@@ -32,7 +32,7 @@ on:
       - 'bin/**'
       - 'dotfiles/**'
       - 'tests/**'
-      - '*.bash'
+      - '**/*.bash'
 
 permissions:
   contents: write
@@ -41,11 +41,40 @@ env:
   JOB_NAME: "HomeSetup-Build"
 
 jobs:
+  set-os-matrix:
+    runs-on: "ubuntu-latest"
+    outputs:
+      matrix-os: ${{ steps.set-matrix-items.outputs.matrix-os }}
+    steps:
+      - name: Show Selected Input
+        run: |
+          echo "Build on Ubuntu-Latest: ${{ inputs.ubuntu || false }}"
+          echo "Build on MacOS-Latest: ${{ inputs.macos || false }}"
+      - name: Set Inclusion Matrix
+        id: set-matrix-items
+        run: |
+          JSON=""
+          if [[ "${{ inputs.ubuntu }}" == "true" ]]; then
+            JSON="\"ubuntu-latest\""
+          fi
+          if [[ "${{ inputs.macos }}" == "true" ]]; then
+            [[ -n "$JSON" ]] && JSON="${JSON}, "
+            JSON="${JSON} \"macos-latest\""
+          fi
+          [[ -z "${JSON}" ]] && JSON="\"ubuntu-latest\""
+          JSON="[${JSON}]"
+          echo "JSON: ${JSON}"
+          echo "matrix-os=$( echo "${JSON}" )" >> $GITHUB_OUTPUT
 
   build:
-    runs-on: 'ubuntu-latest'
+    needs: set-os-matrix
+    strategy:
+      matrix:
+        os: ${{ fromJson(needs.set-os-matrix.outputs.matrix-os) }}
+    runs-on: ${{ matrix.os }}
     env:
-      HHS_LOG_DIR: '/Users/runner/.hhs/log'
+      PREFIX: "${{ github.workspace }}"
+      HHS_LOG_DIR: "${{ matrix.os == 'macos-latest' && '/Users/runner/.config/hhs/log' || '/home/runner/.config/hhs/log' }}"
     steps:
       - uses: actions/checkout@v3
         with:
@@ -58,21 +87,27 @@ jobs:
         run: pip install --upgrade pip
       - name: Install HomeSetup with Prefix
         run: |
-          if ./install.bash -r -p "${{ github.workspace }}"; then
-            echo "${{ github.workspace }}" > "${HOME}/.hhs-prefix"
-            echo -e "\nInstallation information:"
-            echo -e "SHELL: ${SHELL}"
-            echo -e " HOME: ${HOME}"
-            echo -e " USER: ${USER}\n"
-            echo -en "Loading bash profile..."
-            if source "${HOME}"/.bashrc; then echo "OK"; else echo "FAILED"; fi
-            echo "HHS_LOG_DIR=$(echo ${HHS_LOG_DIR})" >> $GITHUB_ENV
-            __hhs tests
-            exit 0
+          if ./install.bash -r -p "${PREFIX}"; then
+            echo "${PREFIX}" > "${HOME}/.hhs-prefix"
+            echo ''
+            echo -e "${YELLOW}Installation information:"
+            echo -e " SHELL: ${SHELL}"
+            echo -e "PREFIX: ${PREFIX}"
+            echo -e "  HOME: ${HOME}"
+            echo -e "  USER: ${USER}"
+            echo -e "  LOGS: ${HHS_LOG_DIR}"
+            echo ''
+            echo -en "${BLUE}Loading bash profile... "
+            if source "${HOME}/.bashrc"; then
+              echo -e "${GREEN}OK${NC}"
+              __hhs tests && exit 0
+            else
+              echo -e "${GREEN}FAILED${NC}"
+            fi
           else
             echo "HHS_LOG_DIR=$(echo ${HOME}/install.log)" >> $GITHUB_ENV
-            exit 1
           fi
+          exit 1
       - name: Upload installation logs (success)
         if: ${{ success() }}
         uses: actions/upload-artifact@v3
